services:
  qdrant_tejarat:
    image: qdrant/qdrant
    container_name: qdrant_tejarat
    restart: unless-stopped
    ports:
      - "6333:6333"  # API port
      - "6334:6334"  # Internal gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT_LOG_LEVEL: INFO  # Logging level (DEBUG, INFO, WARN, ERROR)
      QDRANT__STORAGE__MODE: "on_disk"  # Set storage mode (in_memory or on_disk)
      QDRANT__SERVICE__GRPC_PORT: 6334  # GRPC port setting

volumes:
  qdrant_data:
    driver: local
